# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

right_format = """$kubernetes"""

[kubernetes]
disabled = false
symbol = 'â˜¸ '
format = '[$symbol$context( \($namespace\))]($style)'